"""empty message

Revision ID: df4320ca3a34
Revises: df5b88ea57a7
Create Date: 2019-05-02 23:12:48.001658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4320ca3a34'
down_revision = 'df5b88ea57a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('location', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'location')
    # ### end Alembic commands ###
